"""create first migrations

Revision ID: a3291602cb80
Revises: fdb92f4d3c7f
Create Date: 2026-06-21 20:04:18.093415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3291602cb80'
down_revision: Union[str, Sequence[str], None] = 'fdb92f4d3c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_tg_tg_id_key'), 'user_tg', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_tg_tg_id_key'), 'user_tg', ['tg_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
