"""change_tg_id_to_bigint

Revision ID: dd3126ae1b60
Revises: 1e61fb0721da
Create Date: 2026-07-17 17:44:26.129523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3126ae1b60'
down_revision: Union[str, Sequence[str], None] = '1e61fb0721da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite_cities', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorite_landmarks', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorite_lands', 'user', ['user_id'], ['id'])
    op.alter_column('user_tg', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tg', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'favorite_lands', type_='foreignkey')
    op.drop_constraint(None, 'favorite_landmarks', type_='foreignkey')
    op.drop_constraint(None, 'favorite_cities', type_='foreignkey')
    # ### end Alembic commands ###
