"""create first migrations

Revision ID: fdb92f4d3c7f
Revises: 
Create Date: 2026-06-20 20:28:05.750206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdb92f4d3c7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tg', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('user_tg_user_id_key'), 'user_tg', type_='unique')
    op.drop_column('user_tg', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tg', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_tg_user_id_key'), 'user_tg', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_tg', 'created_at')
    # ### end Alembic commands ###
